### ISSUE TITLE
Scrolling doesn’t work!

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#14]
Strangely this works fine in the app, but not in the SDK. To reproduce use any template that overflows – e.g. template-line-charts

**Comment by daanlouter** [comment]
Which part of the page exactly doesn't scroll for you? Works fine for me

**Comment by robinhouston** [comment]
It seems to be working for me now (which is odd, since nothing has changed).

@theduncanclark Are you still seeing the problem?

**Comment by robinhouston** [comment]
We’ve narrowed it down! It only happens with certain templates, only after resizing the viewport using the handle in the corner, and only when the window is on an external monitor. (Mac Chrome Version 59.0.3071.115)

**Comment by robinhouston** [comment]
The problem seems to be specific to Chrome, and doesn’t occur in “Chrome Canary” Version 61.0.3149.0. Note that it only affects mousewheel scroll, not keyboard scroll.

I think this is almost certainly a browser bug, and it looks as though it will be fixed soon. It may or may not be related to [issue 701178](https://bugs.chromium.org/p/chromium/issues/detail?id=701178)

**Comment by robinhouston** [comment]
The same problem also appears in Safari (including Safari Technology Preview), on the built-in monitor as well an external monitor. Scrolling with the keyboard or the scrollbar works, but mousewheel scrolling does not.

Changing the viewport size using the numeric controls makes it work again.

**Comment by daanlouter** [comment]
I've fixed this by removing `$("#preview").style("pointer-events",none);` on dragstart and `$("#preview").style("pointer-events",null);` and dragstop, when dragging the resize handle. 

It's a weird bug, as the pointer events are properly cleared on drag stop (and I can still select text inside the iframe, but not scroll). Will test tomorrow if removing these lines will affect IE performance.

**Comment by daanlouter** [comment]
Fixed in https://github.com/kiln/flourish/commit/e9fe55c96419a0aad567f69b59d13fe876b85e6a

**Comment by daanlouter** [comment]
(don't have permission to close the issue)

**Comment by robinhouston** [comment]
Will be fixed in SDK 2.6.0
