### ISSUE TITLE
SDK occasionally crashes with the message "Abort trap: 6"

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#18]
I've had this about once a day for the last few days. It appears to happen by itself – i.e. not in response to a change to the code.

**Comment by robinhouston** [comment]
Which template are you running it on?

**Comment by robinhouston** [comment]
Did anything change in your environment when it started happening? Could it be related to the upgrade of Node?

**Comment by robinhouston** [comment]
And can you post the full error message, assuming there’s more to it than that?

**Comment by theduncanclark** [comment]
> Which template are you running it on?

template-line-charts

> Did anything change in your environment when it started happening? Could it be related to the upgrade of Node?

Not sure exactly but the timing does roughly match updating Node.

> And can you post the full error message, assuming there’s more to it than that?

That's the lot!

**Comment by robinhouston** [comment]
I wonder if the fsevents module needs rebuilding after upgrading Node. Try running `npm rebuild`, and let’s see if it carries on happening.

**Comment by robinhouston** [comment]
@theduncanclark Am I right in thinking that you no longer have this problem?

**Comment by theduncanclark** [comment]
Yes, haven't seen it since running rebuild. Thanks!
