### ISSUE TITLE
getpass issue

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-sdk#20]
@annapowellsmith has an issue where the terminal becomes unresponsive when using `flourish register` after the password has been entered. I can’t reproduce this on my machine.

@annapowellsmith: do you see the same issue if you write a simple test script with the [getpass](https://www.npmjs.com/package/getpass) module?

**Comment by robinhouston** [comment]
@annapowellsmith Does this happen on Terminal as well as iTerm2?

**Comment by robinhouston** [comment]
Having discovered that `npm init` also fails in the same way on @annapowellsmith’s terminal, I shall assume for now that this is not a bug in the Flourish SDK.

**Comment by annapowellsmith** [comment]
I think it may be [this issue](https://github.com/npm/npm/issues/17093), related to the Node version.

**Comment by robinhouston** [comment]
Ah, well spotted! I think the original issue is nodejs/node#13557 and the fix is nodejs/node#13560. So it’s broken in Node 8.1.0 and fixed in Node 8.1.1.
