### ISSUE TITLE
Renaming a template data file breaks publish

### ISSUE THREAD

**Issue by annapowellsmith** [kiln/flourish-sdk#24]
For example, I've renamed one of the data files in template-connections-globe.

Now when I run `floc publish` I see:

```
😱  Error from server
😱  ERROR:  null value in column "template_data_table_id" violates not-null constraint
DETAIL:  Failing row contains (376, 5, values, filter1, null, 0, null).
```

If this is a hard limitation then that's fine, but if so it would be nice to make the error message a little friendlier.

**Comment by robinhouston** [comment]
This is really an issue with the Flourish server rather than the SDK, and is related to kiln/flourish#222
