### ISSUE TITLE
Flourish publish should ask for confirmation – at least on core templates 

### ISSUE THREAD

**Issue by annapowellsmith** [kiln/flourish-sdk#26]
Migrating from https://github.com/kiln/flourish/issues/391

We do not allow deployment of the app or marketing site without first checking on staging and typing "confirmed". But it's currently very easy to overwrite a core template with a version that will break everyone's existing visualisations, since for overwriting a template no confirmation is required.

Case in point: Connections globe was accidentally uploaded yesterday to the main site instead of testing or staging. As a result many existing projects are now broken and so far we haven't been able to fix this.

I've always wanted some kind of confirmation step on overwriting a template to avoid this kind of situation. @robinhouston didn't like this idea when we discussed it last year on the grounds that devs would find it annoying and are used to deploying things without confirming.

Perhaps as a compromise we could require a confirmation to overwrite any core (i.e. [`@flourish`](https://app.flourish.studio/@flourish)) template on the live site?

**Comment by robinhouston** [comment]
I propose we prompt for confirmation before overwriting an existing template that has visualisations made from it that haven’t been deleted. This avoids annoying prompts during initial development, but makes it a bit harder to break existing visualisations by mistake.

**Comment by annapowellsmith** [comment]
Something like this:

"Beware! You will irreversibly break existing visualisations based on this template if:

- you have added, deleted or changed data bindings (except edits to names/descriptions)
- you have renamed data tables
- you have reordered columns in data tables.

Are you still happy to publish? y/n"

**Comment by robinhouston** [comment]
I think this problem has been addressed by no longer specifying a username in the `id`, which means that templates can only be published to the `@flourish` account by explicitly specifying `--as=flourish` on publication, making it harder to do without meaning to.

@annapowellsmith Please reopen this issue if you disagree!
