### ISSUE TITLE
Cannot find module './validate_config

### ISSUE THREAD

**Issue by felixmichel** [kiln/flourish-sdk#30]
After updating to version 2.9.0 I get an error when i type `flourish run`.

<img width="615" alt="bildschirmfoto 2017-10-05 um 12 59 34" src="https://user-images.githubusercontent.com/11921821/31225016-743608da-a9d0-11e7-89b9-d27ecb6f15a9.png">

**Comment by robinhouston** [comment]
Oh dear! Version 2.9.1 coming up…

**Comment by robinhouston** [comment]
This is caused by a bug in the version of npm I used to publish this release: npm/npm#18461
