### ISSUE TITLE
Support missing off "columns" property for empty columns binding?

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#31]
Now that we have optional column bindings you can add `optional: true` in the yml and just miss off the `column` property. In the absence of bindings in the SDK preview, when experimenting with an optional binding in a template you end up adding and removing that property a lot in the yml, which works fine.

But it then feels weird that to blank a *columns* binding you can't just drop the property in the same way. All the more so for newbies who will likely be confused that they have to write something like "Data::" – and in quotes or it isn't compatible with yml. Maybe we should support just missing it out?

**Comment by robinhouston** [comment]
This isn’t just an SDK issue: the dataset is required on the server side. I think we should defer this to post kiln/flourish#106.
