### ISSUE TITLE
NPM install 

### ISSUE THREAD

**Issue by zdenekhynek** [kiln/flourish-sdk#33]
Running `npm install -g @flourish/sdk` with NPM 5.3.0 (Node v8.6.0) gives me:

```
npm ERR! code E404
npm ERR! 404 Not Found: @flourish/sdk@latest
...
```

Running the same with NPM v3.10.10 (Node v6.9.5) gives me:

```
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 User not found : @flourish/sdk
npm ERR! 404
npm ERR! 404  '@flourish/sdk' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Maybe I'm missing something?

**Comment by robinhouston** [comment]
Are you sure you're using NPM 5.3.0? The error message says npm v3.10.10.

**Comment by zdenekhynek** [comment]
Yes, i’ve posted two error messages. First one is using 5.3.0, second one
using 3.10.10.

**Comment by robinhouston** [comment]
Thanks for clearing that up. I’m sorry for misreading your original report.

The package certainly exists and is public – see https://www.npmjs.com/package/@flourish/sdk. When I do `npm install -g @flourish/sdk` using NPM 5.3.0 it works as expected. The [entry in the NPM registry](https://registry.npmjs.org/@flourish%2Fsdk) exists and is returned correctly for me.

Does it work if you try again? (Perhaps there was a transient failure on the NPM servers.)

If not, can you get any clues by running `npm install -g @flourish/sdk --verbose`?

**Comment by zdenekhynek** [comment]
@robinhouston thanks for your quick replies.

Turned out I had an _auth authentication token left in my `.npmrc` after using Nexus NPM registry proxy for a different project. Removed it, all works just fine now.
