### ISSUE TITLE
Getting errors while running Tutorial

### ISSUE THREAD

**Issue by sanjayraja** [kiln/flourish-sdk#4]
At first got issues with log.js - some funny characters in the file.
Then stuck at this line while running 
return Promise.all([read_api_token_if_necessary, getSDKVersion()])
		.then(([api_token, sdk_version]) => new Promise(function(resolve, reject) {

I am assuming some sort of API Key is required - but its not documented how to get this.

Register - gives a similar error

**Comment by theduncanclark** [comment]
Thanks for reporting this. Could you let us know what operating system you're using?

**Comment by theduncanclark** [comment]
Also what version of Node you are running?

**Comment by sanjayraja** [comment]
Hi,
I am running mac OS Sierra and node version 4.3.2

Warm Regards,
Sanjay Raja

**Comment by robinhouston** [comment]
Thanks! Currently Node 6 is the earliest supported version.

I’ll file an issue saying we should give an explicit explanation if an older version is used.

If you need to be able to use it with Node 4, can you explain why you can’t upgrade? We can probably make it compatible with Node 4 if there’s a common need for that.

**Comment by robinhouston** [comment]
See #5.
