### ISSUE TITLE
Conditional settings bug when setting starts with `data`

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#45]
I just added a condition to hide a setting if another setting for `data_tables` is set to true. The SDK does not like this: 

`😱  template.yml: “show_if” or “hide_if” property refers to non-existent data binding “data_tables”`

It appears that it has treated my condition as referring to a data binding rather than another setting. Perhaps the SDK is just looking for things that start with `data` rather than `data.`?

**Comment by robinhouston** [comment]
Yes, the problem is that it’s matching against the regular expression `/^data./`, and a dot in a regular expression matches any character!

https://github.com/kiln/flourish-sdk/blob/cf17a5cb62f0d61d4829c8ccf610d4e52b5f311c/lib/validate_config.js#L238
