### ISSUE TITLE
Make it easy to run different builds for development and production

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-sdk#53]
Sometimes you might want to have a different build process for production and development. Typically the production build would be smaller, but take longer to build.

An easy way to make this possible would be to set the `NODE_ENV` environment variable to `production` or `development` before running the build script.

**Comment by timbrock** [comment]
> Sometimes you might want to have a different build process for production and development. Typically the production build would be smaller, but take longer to build.

Disabling uglify on development also makes it easier to debug.
