### ISSUE TITLE
Require confirmation to assign a version number for the first time

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-sdk#54]
The first time you publish a template with a version number that didn’t previously have one, you should republish the *previous* version of the template in order to fix its version number.

It’s easy to get this wrong. We should require explicit confirmation when you assign a version number for the first time.

(Another option would be to have a new command `flourish assign-version-number` or something, and require a version number to have been assigned before a template can be published with a version number.)

**Comment by timbrock** [comment]
> Another option would be to have a new command `flourish assign-version-number` or something, and require a version number to have been assigned before a template can be published with a version number

What do you mean by "assigned" here?

**Comment by robinhouston** [comment]
> What do you mean by "assigned" here?

I mean assigned using `flourish assign-version-number`.

**Comment by timbrock** [comment]
> I mean assigned using `flourish assign-version-number`, which would assign an explicit version number to the currently-live version of the template.

If you could do that like... right now... that would be helpful?

**Comment by robinhouston** [comment]
> If you could do that like... right now...

Done. 😀
