### ISSUE TITLE
`flourish login` not working on Node 10.7.0 (WSL)

### ISSUE THREAD

**Issue by hughsk** [kiln/flourish-sdk#56]
Running `flourish login` breaks before it has the chance to send a login request to the server:

```
$ flourish login
Email:
Password:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:369:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The error appears to be coming from the [`getpass`](https://github.com/arekinath/node-getpass) package: the `rtty` stream emits an error the tick [after it is closed](https://github.com/arekinath/node-getpass/blob/e219fae3a4458a1aa4b84002539265a6a1475267/lib/index.js#L97-L100).

This behavior only seems to be occurring for me when using Node v10 -- switching to Node v8 works around the issue. This makes me suspect that it's related to this bug in Node: https://github.com/nodejs/node/issues/22814

I also don't believe the `getpass` package works on Windows due to its [reliance on `/dev/tty`](https://github.com/arekinath/node-getpass/blob/e219fae3a4458a1aa4b84002539265a6a1475267/lib/index.js#L105-L123) instead of `process.stdin` and `process.stdout`. Perhaps the best solution is to replace `getpass` with a package that works in Windows and Node v10?

Thanks! :)

**Comment by robinhouston** [comment]
> Perhaps the best solution is to replace `getpass` with a package that works in Windows and Node v10?
Do you know of one?

**Comment by robinhouston** [comment]
It looks like NPM uses the [read](https://www.npmjs.com/package/read) package with the `silent: true` option – though this has its own problems, e.g. npm/read#34. Still, less bad than not working at all with Node 10!
