### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by skymen** [kiln/flourish-sdk#75]
Trying to install the package fails with a 404 error
`'@flourish/interpreter@^6.0.3' is not in this registry.`

And on npm, https://www.npmjs.com/package/@flourish/interpreter returns a 404 error

**Comment by oampo** [comment]
Thanks for reporting this @skymen. I've just pushed out a new version of the SDK (3.17.1) which should fix this. Can you try installing again, and if you have any more problems then reopen the ticket and I'll take another look.

**Comment by skymen** [comment]
This fixed it 👌
