### ISSUE TITLE
There’s no link to /preview on narrow windows

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-sdk#8]

**Comment by robinhouston** [comment]
Now there isn’t a link to `/preview` on *any* size of window, so I suppose in that sense this is no longer an issue.

@daanlouter @theduncanclark Was this a deliberate decision?

**Comment by daanlouter** [comment]
I think it'd be nice to have a button to /preview in the SDK. We could add a button like this in the header? (where "Export & Publish" normally sits)

<img width="124" alt="screen shot 2018-04-12 at 17 15 01" src="https://user-images.githubusercontent.com/3636117/38690059-1a4a3e2e-3e75-11e8-9c5e-50d4f7aa01a2.png">

**Comment by theduncanclark** [comment]
I regularly feel sad the link is gone!

We should totally reinstate it.

But I think Anna has come around the view that we should reinstate it in the editor too, so perhaps we should do it in the same way in both places? 

(Not totally sure about “preview” as a special SDK thing as it’s not really previewing the template so much as the current viz. The more natural analog for export and publish might be “publish” or “upload” to actually publish the template.)

**Comment by theduncanclark** [comment]
See https://github.com/kiln/flourish/issues/1400
