### ISSUE TITLE
@flourish/layout doesn't install - it seems to be using a private package

### ISSUE THREAD

**Issue by git-ashish** [kiln/flourish-sdk#88]
Hello,

I am working on a client project and we are unable to use the [layout module](https://developers.flourish.studio/sdk/getting-started/using-modules/#flourishlayout). It is listed as a public module however it seems to be using a [private package utils-color](https://www.npmjs.com/package/@flourish/layout?activeTab=dependencies). Because of this, we are unable to install the layout module and use it for basic purposes like header, footer and legend layouts.

Could you please suggest a solution?

Thanks,
Ashish

**Comment by daanlouter** [comment]
Hi @git-ashish, we've made `@flourish/utils-color` public now, so hopefully this will fix your problem.

**Comment by git-ashish** [comment]
Thanks for such a quick response @daanlouter! Unfortunately, the next error shows up as:

`Error: Could not resolve './core/init.js' from node_modules/@flourish/layout/src/index.js`

<img width="1199" alt="image" src="https://github.com/kiln/flourish-sdk/assets/2697421/2de5e012-2bce-4112-8c09-d4e664c03a77">

![image](https://github.com/kiln/flourish-sdk/assets/2697421/d518a38f-7e5e-4626-8e12-7473de5998c7)

What do you suggest?
Thanks!
