### ISSUE TITLE
Remove "Unexpected JSON message" warnings from console

### ISSUE THREAD

**Issue by aendra-rininsland** [kiln/flourish-sdk#92]
While developing I endlessly get notices like this in my logs:

<img width="851" alt="image" src="https://github.com/kiln/flourish-sdk/assets/185041/eba2c710-9620-4bdb-ad5a-951450da8ea1">

AFAICT it's because of the React Dev Tools heartbeat process, which causes Flourish SDK to print it in the console as a warning.

I could just disable the React Dev Tools extension but I use it while developing. I'd submit a PR to fix it here, but the [file in question](https://github.com/kiln/flourish-sdk/blob/74c20f8122f4b6e58734c65c48609d7cd79ae9ed/site/script.js) doesn't really seem to be part of the repo (I suspect it's copied from another Flourish repo into here). 

One option would be to use the [npm debug module](https://www.npmjs.com/package/debug) in script.js so debug messages like that only appear if `localStorage.debug = 'flourish:*'` or some such.

**Comment by markl-canva** [comment]
Hi @aendra-rininsland - thanks for reporting this; it's been annoying for me too! We have a fix for this, and I expect that we will release a new version of this package with that fix on Friday.

**Comment by markl-canva** [comment]
Hi @aendra-rininsland - if you try updating the Flourish SDK to 4.2.0, hopefully this problem should be gone. If not, please let me know and we'll try to figure out why not!

**Comment by aendra-rininsland** [comment]
Oh amazing! Just updated and it seems resolved now! Thanks so much! 🙌
