### ISSUE TITLE
Failed `flourish publish` command output is unhelpful

### ISSUE THREAD

**Issue by aendra-rininsland** [kiln/flourish-sdk#93]
Often when `flourish publish` fails, you get little more than an error code and a generic error message:

![image](https://github.com/kiln/flourish-sdk/assets/185041/a0ad9070-f3ae-4828-841d-be817f4db4a2)

Even with the `--debug` flag it doesn't provide any extra info.

As someone who is typically asked to help people publish these templates on a deadline, the lack of verbosity in these messages frequently makes my life difficult.

**Comment by markl-canva** [comment]
Hi @aendra-rininsland - there is a server-side fix for this problem, which we're deploying today. If you still see opaque 500 errors like this tomorrow or later, please let us know and we'll investigate, but hopefully this will be resolved soon.

**Comment by markl-canva** [comment]
As an update, I'm afraid we had to roll-back today's deploy because of a bad bug in one of the other changes, but hopefully we'll redeploy tomorrow morning, so it'll be a little longer before this is fixed. Sorry about that.

**Comment by markl-canva** [comment]
This fix for this is deployed again now, so I'll close the issue.

**Comment by aendra-rininsland** [comment]
That helps quite a lot! Thank you!
